/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2024-01-17 08:10:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar", Long.valueOf(1700568224554L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1700568222909L));
    _jspx_dependants.put("/WEB-INF/views/board/includes/footer.jsp", Long.valueOf(1703722701320L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528824936000L));
    _jspx_dependants.put("/WEB-INF/views/board/includes/header.jsp", Long.valueOf(1703722701333L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Multipurpose</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i%7CRajdhani:400,600,700\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/loader/loaders.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/resources/dist/css/font-awesome/font-awesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/aos/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/swiper/swiper.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/lightgallery.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"http://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/dist/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/loaders.css.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/aos.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/swiper.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/lightgallery-all.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/dist/js/main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".blink {\r\n");
      out.write("	animation: blinker 1s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes blinker { 50% \r\n");
      out.write("{\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"css-loader\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"loader-inner line-scale d-flex align-items-center justify-content-center\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<header class=\"position-absolute w-100\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"top-header d-none d-sm-flex justify-content-between align-items-center\">\r\n");
      out.write("				<div class=\"contact\">\r\n");
      out.write("					<i class=\"fa fa-phone\" aria-hidden=\"true\"><a href=\"tel:+8201062975120\" class=\"tel\">01062975120</a></i> \r\n");
      out.write("					<i class=\"fa fa-envelope\" aria-hidden=\"true\"><a href=\"mailto:terran4805@gmail.com\">terran4805@gmail.com</a></i> \r\n");
      out.write("				</div>\r\n");
      out.write("				<nav class=\"d-flex aic\">\r\n");
      out.write("					<ul class=\"nav social d-none d-md-flex\">\r\n");
      out.write("						<li id=\"local-time\"></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					\r\n");
      out.write("					");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav class=\"navbar navbar-expand-md navbar-light\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"/\"><img\r\n");
      out.write("					src=\"/resources/dist/images/logo.png\" width=50%; alt=\"Multipurpose\"></a>\r\n");
      out.write("				<div class=\"group d-flex align-items-center\">\r\n");
      out.write("					<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("						data-target=\"#navbarSupportedContent\"\r\n");
      out.write("						aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("						aria-label=\"Toggle navigation\">\r\n");
      out.write("						<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<a class=\"login-icon d-sm-none\" href=\"#\"><i class=\"fa fa-user\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<a class=\"search-icon d-none d-md-block\" href=\"#\"><i\r\n");
      out.write("					class=\"fa fa-search\"></i></a>\r\n");
      out.write("				<div class=\"collapse navbar-collapse justify-content-end\"\r\n");
      out.write("					id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav\">\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("						");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						");
      if (_jspx_meth_sec_005fauthorize_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"/\">메인으로</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"/about\">회사\r\n");
      out.write("								주소</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"/service\">회사\r\n");
      out.write("								서비스</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"/introduce\">회사\r\n");
      out.write("								소개</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<form class=\"bg-white search-form\" method=\"get\" id=\"searchform\">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<input class=\"field form-control\" id=\"s\" name=\"s\" type=\"text\"\r\n");
      out.write("								placeholder=\"Search\"> <span class=\"input-group-btn\">\r\n");
      out.write("								<input class=\"submit btn btn-primary\" id=\"searchsubmit\"\r\n");
      out.write("								name=\"submit\" type=\"submit\" value=\"Search\">\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<section class=\"hero\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12 offset-md-1 col-md-11\">\r\n");
      out.write("					<div class=\"swiper-container hero-slider\">\r\n");
      out.write("						<div class=\"swiper-wrapper\">\r\n");
      out.write("							<div class=\"swiper-slide slide-content d-flex align-items-center\">\r\n");
      out.write("								<div class=\"single-slide\">\r\n");
      out.write("									<h1 data-aos=\"fade-right\" data-aos-delay=\"200\">저희 회사의 위치를\r\n");
      out.write("										알고 싶으시다면</h1>\r\n");
      out.write("									<a data-aos=\"fade-right\" data-aos-delay=\"900\" href=\"/about\"\r\n");
      out.write("										class=\"btn btn-primary\">회사 위치 보기</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div></div>\r\n");
      out.write("							<div class=\"swiper-slide slide-content d-flex align-items-center\">\r\n");
      out.write("								<div class=\"single-slide\">\r\n");
      out.write("									<h1 data-aos=\"fade-right\" data-aos-delay=\"200\">서비스를 받고\r\n");
      out.write("										싶으시다면</h1>\r\n");
      out.write("									<a data-aos=\"fade-right\" data-aos-delay=\"900\" href=\"/service\"\r\n");
      out.write("										class=\"btn btn-primary\">서비스 보기</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div></div>\r\n");
      out.write("							<div class=\"swiper-slide slide-content d-flex align-items-center\">\r\n");
      out.write("								<div class=\"single-slide\">\r\n");
      out.write("									<h1 data-aos=\"fade-right\" data-aos-delay=\"200\">회사 소개를 보고\r\n");
      out.write("										싶으시다면</h1>\r\n");
      out.write("									<a data-aos=\"fade-right\" data-aos-delay=\"900\" href=\"/introduce\"\r\n");
      out.write("										class=\"btn btn-primary\">회사 소개 보기</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<span class=\"arr-left\"><i class=\"fa fa-angle-left\"></i></span> <span\r\n");
      out.write("				class=\"arr-right\"><i class=\"fa fa-angle-right\"></i></span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"texture\"></div>\r\n");
      out.write("		<div class=\"diag-bg\"></div>\r\n");
      out.write("	</section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"cta\" data-aos=\"fade-up\" data-aos-delay=\"0\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"cta-content d-xl-flex align-items-center justify-content-around text-center text-xl-left\">\r\n");
      out.write("			<div class=\"content\" data-aos=\"fade-right\" data-aos-delay=\"200\">\r\n");
      out.write("				<h2>회사 소식을 보고 싶다면</h2>\r\n");
      out.write("				<p>지금 바로 회사 소식을 구독하세요</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"subscribe-btn\" data-aos=\"fade-left\" data-aos-delay=\"400\"\r\n");
      out.write("				data-aos-offset=\"0\">\r\n");
      out.write("				<a href=\"/about\" class=\"btn btn-primary\">뉴스레터 구독하기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"testimonial-and-clients\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"testimonials\">\r\n");
      out.write("			<div class=\"swiper-container test-slider\">\r\n");
      out.write("				<div class=\"swiper-wrapper\">\r\n");
      out.write("					<div class=\"swiper-slide text-center\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"offset-lg-1 col-lg-10\">\r\n");
      out.write("								<div class=\"test-img\" data-aos=\"fade-up\" data-aos-delay=\"0\"\r\n");
      out.write("									data-aos-offset=\"0\">\r\n");
      out.write("									<img src=\"resources/dist/images/star.png\" alt=\"Testimonial 1\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<h5 data-aos=\"fade-up\" data-aos-delay=\"200\"\r\n");
      out.write("									data-aos-duration=\"600\" data-aos-offset=\"0\">star</h5>\r\n");
      out.write("								<p data-aos=\"fade-up\" data-aos-delay=\"600\"\r\n");
      out.write("									data-aos-duration=\"600\" data-aos-offset=\"0\">\r\n");
      out.write("									Twinkle, twinkle little star<br> How I wonder what you are<br>\r\n");
      out.write("									Up above the world so high<br> Like a diamond in the sky<br>\r\n");
      out.write("									Twinkle, twinkle little star<br> How I wonder what you are\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"test-pagination\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"recent-posts\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1 class=\"title-primary text-center\">Event</h1>\r\n");
      out.write("		<div class=\"row\" id=\"daumbook\"></div>\r\n");
      out.write("		<div class=\"text-center\">\r\n");
      out.write("			<a href=\"http://www.daum.net\" class=\"btn btn-primary\"\r\n");
      out.write("				id=\"remain-time\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"cta cta2\" data-aos=\"fade-up\" data-aos-delay=\"0\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"cta-content d-xl-flex align-items-center justify-content-around text-center text-xl-left\">\r\n");
      out.write("			<div class=\"content\" data-aos=\"fade-right\" data-aos-delay=\"200\">\r\n");
      out.write("				<h2>저희 회사의 소식을 알고 싶다면</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"subscribe-btn\" data-aos=\"fade-left\" data-aos-delay=\"400\"\r\n");
      out.write("				data-aos-offset=\"0\">\r\n");
      out.write("				<a href=\"/about\" class=\"btn btn-primary\">회사 소식 구독</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script>\r\n");
      out.write("    \r\n");
      out.write("    //책정보 출력\r\n");
      out.write("        function getBest() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"get\",\r\n");
      out.write("                url: \"https://dapi.kakao.com/v3/search/book\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    query: \"별\",\r\n");
      out.write("                    target: \"title\",\r\n");
      out.write("                    size: 8\r\n");
      out.write("                },\r\n");
      out.write("                headers: { Authorization: \"KakaoAK 26e253cda867120a05230e16f30c137e\" },\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("                    for (let i = 0; i < data.documents.length; i++) {\r\n");
      out.write("                        let book = \"\";\r\n");
      out.write("                        if (i % 2 == 0) {\r\n");
      out.write("                            book += '<div class=\"col-lg-6\">';\r\n");
      out.write("                            book += '    <div class=\"single-rpost d-sm-flex align-items-center\" dat-aos-delay=\"200\" data-aos=\"fade-right\" data-aos-duration=\"800\">';\r\n");
      out.write("                            book += '        <div class=\"post-content\">';\r\n");
      out.write("                            book += '            <h3><a href =' + data.documents[i].url + \">\" + data.documents[i].title + '</a></h3>';\r\n");
      out.write("                            book += '            <p><a href =' + data.documents[i].url + \">\" + data.documents[i].price.toLocaleString('ko-KR') + '</a></p>';\r\n");
      out.write("                            book += '            <a class=\"post-btn\" href=\"' + data.documents[i].url + '\"><i class=\"fa fa-arrow-right\"></i></a>';\r\n");
      out.write("                            book += '        </div>';\r\n");
      out.write("                            book += '        <div class=\"post-thumb\">';\r\n");
      out.write("                            book += '            <img class=\"img-fluid\" src=\"' + data.documents[i].thumbnail + '\" alt=\"Post 1\">';\r\n");
      out.write("                            book += '        </div>';\r\n");
      out.write("                            book += '    </div>';\r\n");
      out.write("                            book += '</div>';\r\n");
      out.write("                        } else {\r\n");
      out.write("                            book += '<div class=\"col-lg-6\">';\r\n");
      out.write("                            book += '    <div class=\"single-rpost d-sm-flex align-items-center\" dat-aos-delay=\"200\" data-aos=\"fade-left\" data-aos-duration=\"800\">';\r\n");
      out.write("                            book += '        <div class=\"post-thumb\">';\r\n");
      out.write("                            book += '            <img class=\"img-fluid\" src=\"' + data.documents[i].thumbnail + '\" alt=\"Post 1\">';\r\n");
      out.write("                            book += '        </div>';\r\n");
      out.write("                            book += '        <div class=\"post-content\">';\r\n");
      out.write("                            book += '            <h3><a href =' + data.documents[i].url + \">\" + data.documents[i].title + '</a></h3>';\r\n");
      out.write("                            book += '            <p><a href =' + data.documents[i].url + \">\" + data.documents[i].price.toLocaleString('ko-KR') + '</a></p>';\r\n");
      out.write("                            book += '            <a class=\"post-btn\" href=\"' + data.documents[i].url + '\"><i class=\"fa fa-arrow-right\"></i></a>';\r\n");
      out.write("                            book += '        </div>';\r\n");
      out.write("                            book += '    </div>';\r\n");
      out.write("                            book += '</div>';\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        $(\"#daumbook\").append(book);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("	\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            getBest();\r\n");
      out.write("\r\n");
      out.write("        })\r\n");
      out.write("       \r\n");
      out.write("	//카운트다운    \r\n");
      out.write("    setInterval(function () {\r\n");
      out.write("        let standardTime = new Date(\"2023-12-27 00:00:00\");\r\n");
      out.write("        let todayTime = new Date();\r\n");
      out.write("        let getDiffdayzero = '';\r\n");
      out.write("        let getDiffhourzero = '';\r\n");
      out.write("        let getDiffminuteszero = '';\r\n");
      out.write("        let getDiffsecondzero = '';\r\n");
      out.write("        let diff = standardTime-todayTime;\r\n");
      out.write("        let diffDay = Math.floor(diff / (1000 * 60 * 60 * 24));\r\n");
      out.write("        let diffHour = Math.floor((diff / (1000 * 60 * 60)) % 24);\r\n");
      out.write("        let diffMin = Math.floor((diff / (1000 * 60)) % 60);\r\n");
      out.write("        let diffSec = Math.floor(diff / 1000 % 60);\r\n");
      out.write("        if (diffDay < 10) {\r\n");
      out.write("            getDiffdayzero += '0'\r\n");
      out.write("        }\r\n");
      out.write("        if (diffHour < 10) {\r\n");
      out.write("            getDiffhourzero += '0'\r\n");
      out.write("        }\r\n");
      out.write("        if (diffMin < 10) {\r\n");
      out.write("            getDiffminuteszero += '0'\r\n");
      out.write("        }\r\n");
      out.write("        if (diffSec < 10) {\r\n");
      out.write("            getDiffsecondzero += '0'\r\n");
      out.write("        }\r\n");
      out.write("		if(diff <= 0){\r\n");
      out.write("		JavaScript: void(0)\r\n");
      out.write("		let remaintime = \"00:00:00:00\";\r\n");
      out.write("		document.querySelector(\"#remain-time\").innerHTML = remaintime;\r\n");
      out.write("		document.querySelector(\"#remain-time\").removeAttribute('href');\r\n");
      out.write("		} else {\r\n");
      out.write("		  let remaintime = '<b class=\"blink\">' + getDiffdayzero + diffDay + ':' + getDiffhourzero + diffHour + ':' + getDiffminuteszero + diffMin + ':' + getDiffsecondzero + diffSec + '</b>';\r\n");
      out.write("		  \r\n");
      out.write("        document.querySelector(\"#remain-time\").innerHTML = remaintime;\r\n");
      out.write("		  }\r\n");
      out.write("		  \r\n");
      out.write("    }\r\n");
      out.write("        , 1000);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-widgets\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8 col-xl-4\">\r\n");
      out.write("                    <div class=\"single-widget contact-widget\" data-aos=\"fade-up\" data-aos-delay=\"0\">\r\n");
      out.write("                        <h6 class=\"widget-tiltle\">&nbsp;</h6>\r\n");
      out.write("                        <p><a href=\"/\"><img src=\"/resources/dist/images/logo.png\" alt=\"Multipurpose\"></a></p>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media\">\r\n");
      out.write("                            <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                            <div class=\"media-body ml-5\">\r\n");
      out.write("                                <h6>메일</h6>\r\n");
      out.write("                                <a href=\"mailto:terran4805@gmail.com\">terran4805@gmail.com</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"media\">\r\n");
      out.write("                            <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                            <div class=\"media-body ml-5\">\r\n");
      out.write("                                <h6>전화</h6>\r\n");
      out.write("                                <a href=\"tel:+8201062975120\">01062975120</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-8 col-xl-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"single-widget tags-widget\" data-aos=\"fade-up\" data-aos-delay=\"800\">\r\n");
      out.write("                            <h6 class=\"widget-tiltle\">메뉴 이동</h6>\r\n");
      out.write("                            <a href=\"/\">HOME</a>\r\n");
      out.write("                            <a href=\"/about\">ABOUT</a>\r\n");
      out.write("                            <a href=\"/service\">SERVICE</a>\r\n");
      out.write("                            <a href=\"/introduce\">INTRODUCE</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("</footer>    \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("setInterval(function () {\r\n");
      out.write("	 let now = new Date();\r\n");
      out.write("     let year = now.getFullYear();\r\n");
      out.write("     let month = now.getMonth() + 1;\r\n");
      out.write("     let weekday = ['일', '월', '화', '수', '목', '금', '토'];\r\n");
      out.write("     let week = weekday[now.getDay()];\r\n");
      out.write("     let date = now.getDate();\r\n");
      out.write("     let hour = now.getHours();\r\n");
      out.write("     let minute = now.getMinutes();\r\n");
      out.write("     let second = now.getSeconds();\r\n");
      out.write("     let Monthzero = '';\r\n");
      out.write("     let Datezero = '';\r\n");
      out.write("     let Hourzero = '';\r\n");
      out.write("     let Minutezero = '';\r\n");
      out.write("     let Secondzero = '';\r\n");
      out.write("     if (month < 10) {\r\n");
      out.write("       Monthzero += '0'\r\n");
      out.write("     }\r\n");
      out.write("     if (date < 10) {\r\n");
      out.write("       Datezero += '0'\r\n");
      out.write("     }\r\n");
      out.write("     if (hour < 10) {\r\n");
      out.write("       Hourzero += '0'\r\n");
      out.write("     }\r\n");
      out.write("     if (minute < 10) {\r\n");
      out.write("       Minutezero += '0'\r\n");
      out.write("     }\r\n");
      out.write("     if (second < 10) {\r\n");
      out.write("       Secondzero += '0'\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     let time = year + '-' + Monthzero + month + '-' + Datezero + date + ' (' + week + ') ' + Hourzero + hour + '<b class=\"blink\">:</b>' + Minutezero + minute + '<b class=\"blink\">:</b>' + Secondzero + second;\r\n");
      out.write("\r\n");
      out.write("     document.querySelector('#local-time').innerHTML = time;\r\n");
      out.write("  }, 1000);\r\n");
      out.write("</script>\r\n");
      out.write("    <!--Plugins-->\r\n");
      out.write("    \r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/board/includes/header.jsp(70,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("					<a href=\"/logout\" class=\"login\"><i class=\"fa fa-user\"\r\n");
        out.write("						aria-hidden=\"true\"></i>로그아웃</a>\r\n");
        out.write("					");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/board/includes/header.jsp(74,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("					<a href=\"/login\" class=\"login\"><i class=\"fa fa-user\"\r\n");
        out.write("						aria-hidden=\"true\"></i>로그인</a>\r\n");
        out.write("					");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/board/includes/header.jsp(100,6) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("						<a href=\"/\"><b class=\"blink\">방문자</b></a>님 환영합니다.\r\n");
        out.write("						");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent(null);
      // /WEB-INF/views/board/includes/header.jsp(103,6) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("						<a href=\"/admin/member/myPage\"><b class=\"blink\">");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f3, _jspx_page_context))
          return true;
        out.write("</b></a>님 환영합니다.\r\n");
        out.write("						");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f3);
      // /WEB-INF/views/board/includes/header.jsp(104,54) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.member.userName");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }
}
