/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2024-01-17 09:18:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myCompany_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/WEB-INF/views/admin/company/../includes/menu.jsp", Long.valueOf(1703722700391L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/company/../includes/header.jsp", Long.valueOf(1703722700375L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/company/../includes/footer.jsp", Long.valueOf(1703722700346L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar", Long.valueOf(1700568224554L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1700568222909L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528824936000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Material Able bootstrap admin template by Codedthemes</title>\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 10]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("      <![endif]-->\r\n");
      out.write("    <!-- Meta -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"keywords\" content=\"bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive\" />\r\n");
      out.write("    <meta name=\"author\" content=\"Codedthemes\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"/resources/assets/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <!-- Google font-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- waves.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("    <!-- Required Fremwork -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- waves.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("    <!-- themify icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/icon/themify-icons/themify-icons.css\">\r\n");
      out.write("    <!-- font-awesome-n -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/font-awesome-n.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- scrollbar.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/jquery.mCustomScrollbar.css\">\r\n");
      out.write("    <!-- Style.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/style.css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/assets/js/jquery/jquery.min.js \"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("  .blink {\r\n");
      out.write("        animation: blinker 1s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes blinker {\r\n");
      out.write("        50% {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Pre-loader start -->\r\n");
      out.write("    <div class=\"theme-loader\">\r\n");
      out.write("        <div class=\"loader-track\">\r\n");
      out.write("            <div class=\"preloader-wrapper\">\r\n");
      out.write("                <div class=\"spinner-layer spinner-blue\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"spinner-layer spinner-red\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"spinner-layer spinner-yellow\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"spinner-layer spinner-green\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Pre-loader end -->\r\n");
      out.write("    <div id=\"pcoded\" class=\"pcoded\">\r\n");
      out.write("        <div class=\"pcoded-overlay-box\"></div>\r\n");
      out.write("        <div class=\"pcoded-container navbar-wrapper\">\r\n");
      out.write("            <nav class=\"navbar header-navbar pcoded-header\">\r\n");
      out.write("                <div class=\"navbar-wrapper\">\r\n");
      out.write("                    <div class=\"navbar-logo\">\r\n");
      out.write("                        <a class=\"mobile-menu waves-effect waves-light\" id=\"mobile-collapse\" href=\"#!\">\r\n");
      out.write("                            <i class=\"ti-menu\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"mobile-search waves-effect waves-light\">\r\n");
      out.write("                            <div class=\"header-search\">\r\n");
      out.write("                                <div class=\"main-search morphsearch-search\">\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <span class=\"input-group-prepend search-close\"><i class=\"ti-close input-group-text\"></i></span>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Enter Keyword\">\r\n");
      out.write("                                        <span class=\"input-group-append search-btn\"><i class=\"ti-search input-group-text\"></i></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"/admin/\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/assets/images/logo.png\" alt=\"Theme-Logo\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a class=\"mobile-options waves-effect waves-light\">\r\n");
      out.write("                            <i class=\"ti-more\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"navbar-container container-fluid\">\r\n");
      out.write("                        <ul class=\"nav-left\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"sidebar_toggle\"><a href=\"javascript:void(0)\"><i class=\"ti-menu\"></i></a></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#!\" onclick=\"javascript:toggleFullScreen()\" class=\"waves-effect waves-light\">\r\n");
      out.write("                                    <i class=\"ti-fullscreen\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul class=\"nav-right\">\r\n");
      out.write("                            <li class=\"header-notification\">\r\n");
      out.write("                                <a href=\"#!\" class=\"waves-effect waves-light\">\r\n");
      out.write("                                    <i class=\"ti-bell\"></i>\r\n");
      out.write("                                    <span class=\"badge bg-c-red\"></span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"show-notification\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <h6>Notifications</h6>\r\n");
      out.write("                                        <label class=\"label label-danger\">New</label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"/resources/assets/images/avatar-2.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h5 class=\"notification-user\">John Doe</h5>\r\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\r\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"/resources/assets/images/avatar-4.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h5 class=\"notification-user\">Joseph William</h5>\r\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\r\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"/resources/assets/images/avatar-3.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h5 class=\"notification-user\">Sara Soudein</h5>\r\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\r\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"user-profile header-notification\">\r\n");
      out.write("                                <a href=\"#!\" class=\"waves-effect waves-light\">\r\n");
      out.write("                                    <img src=\"/resources/assets/images/avatar-4.jpg\" class=\"img-radius\" alt=\"User-Profile-Image\">\r\n");
      out.write("                                    <span>");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("                                    <i class=\"ti-angle-down\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"show-notification profile-notification\">\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <a href=\"/\">\r\n");
      out.write("                                            <i class=\"ti-user\"></i> MainPage\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <a href=\"/admin/member/myPage\">\r\n");
      out.write("                                            <i class=\"ti-user\"></i> Profile\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"pcoded-main-container\">\r\n");
      out.write("                <div class=\"pcoded-wrapper\">\r\n");
      out.write("                    <nav class=\"pcoded-navbar\">\r\n");
      out.write("                        <div class=\"sidebar_toggle\"><a href=\"#\"><i class=\"icon-close icons\"></i></a></div>\r\n");
      out.write("                        <div class=\"pcoded-inner-navbar main-menu\">\r\n");
      out.write("                            \r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("								<div class=\"\">\r\n");
      out.write("                                <div class=\"main-menu-header\">\r\n");
      out.write("                                    <img class=\"img-80 img-radius\" src=\"/resources/assets/images/avatar-4.jpg\" alt=\"User-Profile-Image\">\r\n");
      out.write("                                    <div class=\"user-details\">\r\n");
      out.write("                                        <span id=\"more-details\">");
      if (_jspx_meth_sec_005fauthentication_005f1(_jspx_page_context))
        return;
      out.write("<i class=\"fa fa-caret-down\"></i></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"main-menu-content\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li class=\"more-details\">\r\n");
      out.write("                                        	<a href=\"/\"><i class=\"ti-user\"></i>MainPage</a>\r\n");
      out.write("                                            <a href=\"/admin/member/myPage\"><i class=\"ti-user\"></i>View Profile</a>\r\n");
      out.write("                                            <a href=\"#!\"><i class=\"ti-settings\"></i>Settings</a>\r\n");
      out.write("                                            ");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											");
      if (_jspx_meth_sec_005fauthorize_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pcoded-navigation-label\">Left Time</div>\r\n");
      out.write("                             <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                            	<li class=\"\">\r\n");
      out.write("                        			<a href=\"#\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                   <span class=\"pcoded-micon\"><i class=\"fa fa-clock-o\"></i><b>D</b></span>\r\n");
      out.write("                                   <span id=\"remain-time\" class=\"pcoded-mtext\"></span>\r\n");
      out.write("                                   <span class=\"pcoded-mcaret\"></span> \r\n");
      out.write("                                   </a> \r\n");
      out.write("                                </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                              \r\n");
      out.write("                             <div class=\"pcoded-navigation-label\">Time</div>\r\n");
      out.write("                             <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                             \r\n");
      out.write("                             	<li class=\"active\">\r\n");
      out.write("                        			<a href=\"#\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                   <span class=\"pcoded-micon\"><i class=\"fa fa-calendar\"></i><b>D</b></span>\r\n");
      out.write("                                   <span id=\"local-time1\" class=\"pcoded-mtext\"></span>\r\n");
      out.write("                                   <span class=\"pcoded-mcaret\"></span> \r\n");
      out.write("                                   </a> \r\n");
      out.write("                                </li>\r\n");
      out.write("                             	<li class=\"active\">\r\n");
      out.write("                        			<a href=\"#\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                   <span class=\"pcoded-micon\"><i class=\"fa fa-clock-o\"></i><b>D</b></span>\r\n");
      out.write("                                   <span id=\"local-time2\" class=\"pcoded-mtext\"></span>\r\n");
      out.write("                                   <span class=\"pcoded-mcaret\"></span> \r\n");
      out.write("                                   </a> \r\n");
      out.write("                                </li>\r\n");
      out.write("                             \r\n");
      out.write("                             </ul>\r\n");
      out.write("                            <div class=\"pcoded-navigation-label\">Navigation</div>\r\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                                <li class=\"active\">\r\n");
      out.write("                                    <a href=\"/admin/\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-home\"></i><b>D</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">대시보드</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                       </a>\r\n");
      out.write("                                    \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'diary'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"/admin/accountbook/diary\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-agenda\"></i><b>D</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">다이어리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'board'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"/admin/board/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-list\"></i><b>D</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">게시판관리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'trade'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                     <a href=\"/admin/trade/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                         <span class=\"pcoded-micon\"><i class=\"ti-money\"></i></span>\r\n");
      out.write("                                         <span class=\"pcoded-mtext\">거래명세서</span>\r\n");
      out.write("                                         <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                     </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                  <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'log'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                     <a href=\"/admin/log/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                         <span class=\"pcoded-micon\"><i class=\"ti-agenda\"></i></span>\r\n");
      out.write("                                         <span class=\"pcoded-mtext\">업무일지</span>\r\n");
      out.write("                                         <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                     </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            \r\n");
      out.write("							<div class=\"pcoded-navigation-label }\">UI Element</div>\r\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                                <li class=\"pcoded-hasmenu ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'major' || active == 'member' || active == 'master' || active == 'myCompany' ? 'active pcode-trigger':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-layout-grid2-alt\"></i><b>BC</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">기본정보관리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"pcoded-submenu\">\r\n");
      out.write("	                                     <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'myCompany'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/company/myCompany\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">회사정보관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'major'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/major/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">메이지정보관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'master'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/master/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">마스터코드관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                       </li>\r\n");
      out.write("                                         <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'member'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/member/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">직원관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                       </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            	<div class=\"pcoded-navigation-label }\">UI Element</div>\r\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                                <li class=\"pcoded-hasmenu ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'product' || active == 'master' || active == 'company' ? 'active pcode-trigger':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-layout-grid2-alt\"></i><b>BC</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">업무관리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"pcoded-submenu\">\r\n");
      out.write("	                                     <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'company'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/company/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">납품업체관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'product'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/product/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">물품관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                       	</li>         \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <div class=\"pcoded-content\">\r\n");
      out.write("                        <!-- Page-header start -->\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <div class=\"page-block\">\r\n");
      out.write("                                <div class=\"row align-items-center\">\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                        <div class=\"page-header-title\">\r\n");
      out.write("                                            <h5 class=\"m-b-10\">Dashboard</h5>\r\n");
      out.write("                                            <p class=\"m-b-0\">Welcome to Material Able</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <ul class=\"breadcrumb\">\r\n");
      out.write("                                            <li class=\"breadcrumb-item\">\r\n");
      out.write("                                                <a href=\"/admin/\"> <i class=\"fa fa-home\"></i> </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"breadcrumb-item\"><a href=\"#!\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Page-header end -->\r\n");
      out.write("                        <div class=\"pcoded-inner-content\">\r\n");
      out.write("                            <!-- Main-body start -->\r\n");
      out.write("                            <div class=\"main-body\">\r\n");
      out.write("                                <div class=\"page-wrapper\">\r\n");
      out.write("                                    <!-- Page-body start -->\r\n");
      out.write("                                    <div class=\"page-body\">\r\n");
      out.write("                                    <!-- header End -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<div class=\"col-sm-12\">\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("			<div class=\"card-header\">\r\n");
      out.write("				<h5>회사정보</h5>\r\n");
      out.write("				<span>회사기본정보화면입니다.</span>\r\n");
      out.write("				<div class=\"card-header-right\">\r\n");
      out.write("					<ul class=\"list-unstyled card-option\">\r\n");
      out.write("						<li><i class=\"fa fa fa-wrench open-card-option\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-window-maximize full-card\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-minus minimize-card\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-refresh reload-card\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-trash close-card\"></i></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card-block\">\r\n");
      out.write("			   <form id=\"form\" role=\"form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("				<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"oriCompanySeal\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.companySeal }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-inline\">\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>사업자등록번호</label>\r\n");
      out.write("	                	<input type=\"text\" name=\"taxId\" id=\"taxId\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.taxId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	               	</div>\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>상호(법인명)</label>\r\n");
      out.write("	                	<input type=\"text\" name=\"companyName\" id=\"companyName\" class=\"form-control\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	               	</div>\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>성명</label>\r\n");
      out.write("	                	<input type=\"text\" name=\"ceoName\" id=\"ceoName\" class=\"form-control\" required=\"required\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.ceoName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("               		</div>\r\n");
      out.write("               	</div>\r\n");
      out.write("               	<div class=\"form-inline\">\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>사업장주소</label>\r\n");
      out.write("	                	<div class=\"input-group\">\r\n");
      out.write("							<input type=\"text\" name=\"address\" id=\"address\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							<div class=\"input-group-append\">\r\n");
      out.write("								<button class=\"btn btn-secondary\" type=\"button\" onclick=\"sample3_execDaumPostcode()\">\r\n");
      out.write("									<i class=\"fa fa-search\"></i>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("	               	</div>\r\n");
      out.write("               	</div>               	\r\n");
      out.write("               	\r\n");
      out.write("               	<div class=\"form-group\">\r\n");
      out.write("	               	<div id=\"wrap\" style=\"display:none;border:1px solid;width:100%;height:300px;margin:5px 0;position:relative\">\r\n");
      out.write("						<img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\" id=\"btnFoldWrap\" style=\"cursor:pointer;position:absolute;right:0px;top:-1px;z-index:1\" onclick=\"foldDaumPostcode()\" alt=\"접기 버튼\">\r\n");
      out.write("					</div>\r\n");
      out.write("               	</div>\r\n");
      out.write("               	\r\n");
      out.write("               	\r\n");
      out.write("               	<div class=\"form-inline\">\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>전화번호</label>\r\n");
      out.write("	                	<input type=\"text\" name=\"tel\" id=\"tel\" class=\"form-control\" required=\"required\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	               	</div>\r\n");
      out.write("               	</div>\r\n");
      out.write("               	<div class=\"form-inline\">\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>업태</label>\r\n");
      out.write("	                	<select name=\"bizType\" id=\"bizType\" class=\"form-control\">\r\n");
      out.write("	                	<option value=\"\">선택</option>\r\n");
      out.write("	                	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                	</select>\r\n");
      out.write("	               	</div>\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>종목</label>\r\n");
      out.write("	                	<select name=\"bizItem\" id=\"bizItem\" class=\"form-control\">\r\n");
      out.write("	                	</select>\r\n");
      out.write("	               	</div>\r\n");
      out.write("               	</div>\r\n");
      out.write("               	<div class=\"form-inline\">\r\n");
      out.write("	               	<div class=\"form-group\">\r\n");
      out.write("	                	<label>직인</label>\r\n");
      out.write("	                	<div id=\"image_container\">\r\n");
      out.write("                       		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                       	</div>\r\n");
      out.write("                        <i class=\"fa fa-camera\" style=\"font-size:1.7em;\"></i>\r\n");
      out.write("                       	<input type=\"file\" style=\"display:none;\" accept=\"image/*\" name=\"compSeal\" id=\"companySeal\" class=\"form-control\" onchange=\"setThumbnail(event);\">\r\n");
      out.write("	               	</div>\r\n");
      out.write("               	</div>\r\n");
      out.write("               	<button id=\"modify\" type=\"button\" class=\"btn btn-default btn-sm\">수정</button>\r\n");
      out.write("               	<button id=\"list\" type=\"button\" class=\"btn btn-primary btn-sm\">목록</button>\r\n");
      out.write("               </form>\r\n");
      out.write("           </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("             \r\n");
      out.write("            \r\n");
      out.write("<form id=\"actionForm\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	var bizType = $(\"#bizType option:selected\").val();\r\n");
      out.write("	\r\n");
      out.write("	$(\"#bizType\").on(\"change\", function(){\r\n");
      out.write("\r\n");
      out.write("		let bizType = $(\"#bizType option:selected\").val();\r\n");
      out.write("		\r\n");
      out.write("		bizTypeSelect(bizType);\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function bizTypeSelect(bizType){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:'get',\r\n");
      out.write("			url:'/admin/master/codes/' + bizType + '.json',\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				let html = '';\r\n");
      out.write("				\r\n");
      out.write("				for(let i = 0; i < data.length; i++){\r\n");
      out.write("					//company에 있는 bizItem값이랑 ajax에서 불러온 detailedCode값이랑 같으면.\r\n");
      out.write("					if(data[i].detailedCode == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.bizItem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("						html += '<option value=\"' + data[i].detailedCode + '\" selected>' + data[i].detailedName + '</option>';\r\n");
      out.write("					} else {\r\n");
      out.write("						html += '<option value=\"' + data[i].detailedCode + '\">' + data[i].detailedName + '</option>';\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				$(\"#bizItem\").html(html);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	bizTypeSelect(bizType);\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	$(\".fa-camera\").on(\"click\", function(){\r\n");
      out.write("		$(\"#companySeal\").click();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});//$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("function setThumbnail(event) {\r\n");
      out.write("    var reader = new FileReader();\r\n");
      out.write("	document.querySelector(\"div#image_container\").innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("    reader.onload = function(event) {\r\n");
      out.write("      var img = document.createElement(\"img\");\r\n");
      out.write("      img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("      img.setAttribute(\"width\", 300);\r\n");
      out.write("      document.querySelector(\"div#image_container\").appendChild(img);\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	var formObj = $(\"#form\");\r\n");
      out.write("	var actionFormObj = $(\"#actionForm\");\r\n");
      out.write("	 \r\n");
      out.write("	$(\"#modify\").on(\"click\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("			\r\n");
      out.write("		submitChk = true;\r\n");
      out.write("	\r\n");
      out.write("		formObj.submit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	$(\"#list\").on(\"click\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		submitChk = true;\r\n");
      out.write("		\r\n");
      out.write("		actionFormObj.attr(\"action\", \"list\");\r\n");
      out.write("		actionFormObj.attr(\"method\", \"get\");\r\n");
      out.write("		\r\n");
      out.write("		var pageNumTag = $(\"input[name='pageNum']\").clone();//태그복사\r\n");
      out.write("		var amountTag = $(\"input[name='amount']\").clone();//태그복사\r\n");
      out.write("\r\n");
      out.write("		var typeTag = $(\"input[name='type']\").clone();//태그복사\r\n");
      out.write("		var keywordTag = $(\"input[name='keyword']\").clone();//태그복사\r\n");
      out.write("		\r\n");
      out.write("		// 폼안의 요소를 삭제\r\n");
      out.write("		actionFormObj.empty();\r\n");
      out.write("		actionFormObj.append(pageNumTag);\r\n");
      out.write("		actionFormObj.append(amountTag);\r\n");
      out.write("		actionFormObj.append(typeTag);\r\n");
      out.write("		actionFormObj.append(keywordTag);\r\n");
      out.write("		\r\n");
      out.write("		actionFormObj.submit();\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("submitChk = false;\r\n");
      out.write("window.addEventListener('beforeunload', (event) => {\r\n");
      out.write("	if(!submitChk){\r\n");
      out.write("        // 명세에 따라 preventDefault는 호출해야하며, 기본 동작을 방지합니다.\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("        // 대표적으로 Chrome에서는 returnValue 설정이 필요합니다.\r\n");
      out.write("        event.returnValue = '';\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // 우편번호 찾기 찾기 화면을 넣을 element\r\n");
      out.write("    var element_wrap = document.getElementById('wrap');\r\n");
      out.write("\r\n");
      out.write("    function foldDaumPostcode() {\r\n");
      out.write("        // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("        element_wrap.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function sample3_execDaumPostcode() {\r\n");
      out.write("        // 현재 scroll 위치를 저장해놓는다.\r\n");
      out.write("        var currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    //document.getElementById(\"sample3_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    //document.getElementById(\"sample3_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                //document.getElementById('sample3_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"address\").focus();\r\n");
      out.write("\r\n");
      out.write("                // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("                element_wrap.style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                // 우편번호 찾기 화면이 보이기 이전으로 scroll 위치를 되돌린다.\r\n");
      out.write("                document.body.scrollTop = currentScroll;\r\n");
      out.write("            },\r\n");
      out.write("            // 우편번호 찾기 화면 크기가 조정되었을때 실행할 코드를 작성하는 부분. iframe을 넣은 element의 높이값을 조정한다.\r\n");
      out.write("            onresize : function(size) {\r\n");
      out.write("                element_wrap.style.height = size.height+'px';\r\n");
      out.write("            },\r\n");
      out.write("            width : '100%',\r\n");
      out.write("            height : '100%'\r\n");
      out.write("        }).embed(element_wrap);\r\n");
      out.write("\r\n");
      out.write("        // iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("        element_wrap.style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer Start -->\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Page-body end -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"styleSelector\"> </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Warning Section Starts -->\r\n");
      out.write("    <!-- Older IE warning message -->\r\n");
      out.write("    <!--[if lt IE 10]>\r\n");
      out.write("<div class=\"ie-warning\">\r\n");
      out.write("    <h1>Warning!!</h1>\r\n");
      out.write("    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>\r\n");
      out.write("    <div class=\"iew-container\">\r\n");
      out.write("        <ul class=\"iew-download\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://www.google.com/chrome/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/chrome.png\" alt=\"Chrome\">\r\n");
      out.write("                    <div>Chrome</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"https://www.mozilla.org/en-US/firefox/new/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/firefox.png\" alt=\"Firefox\">\r\n");
      out.write("                    <div>Firefox</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://www.opera.com\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/opera.png\" alt=\"Opera\">\r\n");
      out.write("                    <div>Opera</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"https://www.apple.com/safari/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/safari.png\" alt=\"Safari\">\r\n");
      out.write("                    <div>Safari</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/ie.png\" alt=\"\">\r\n");
      out.write("                    <div>IE (9 & above)</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p>Sorry for the inconvenience!</p>\r\n");
      out.write("</div>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("    <!-- Warning Section Ends -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Required Jquery -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/jquery-ui/jquery-ui.min.js \"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/popper.js/popper.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/bootstrap/js/bootstrap.min.js \"></script>\r\n");
      out.write("    <!-- waves js -->\r\n");
      out.write("    <script src=\"/resources/assets/pages/waves/js/waves.min.js\"></script>\r\n");
      out.write("    <!-- jquery slimscroll js -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/jquery-slimscroll/jquery.slimscroll.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- slimscroll js -->\r\n");
      out.write("    <script src=\"/resources/assets/js/jquery.mCustomScrollbar.concat.min.js \"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- menu js -->\r\n");
      out.write("    <script src=\"/resources/assets/js/pcoded.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/assets/js/vertical/vertical-layout.min.js \"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/script.js \"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("    $(\".sidebar-nav\")\r\n");
      out.write("    .attr(\"class\", \"sidebar-nav navbar-collapse collapse\")\r\n");
      out.write("    .attr(\"aria-expanded\", \"false\")\r\n");
      out.write("    .attr(\"style\", \"height:1px\");\r\n");
      out.write("           \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    setInterval(function () {\r\n");
      out.write("      let now = new Date();\r\n");
      out.write("      let year = now.getFullYear();\r\n");
      out.write("      let month = now.getMonth() + 1;\r\n");
      out.write("      let weekday = ['일', '월', '화', '수', '목', '금', '토'];\r\n");
      out.write("      let week = weekday[now.getDay()];\r\n");
      out.write("      let date = now.getDate();\r\n");
      out.write("      let hour = now.getHours();\r\n");
      out.write("      let minute = now.getMinutes();\r\n");
      out.write("      let second = now.getSeconds();\r\n");
      out.write("      let Monthzero = '';\r\n");
      out.write("      let Datezero = '';\r\n");
      out.write("      let Hourzero = '';\r\n");
      out.write("      let Minutezero = '';\r\n");
      out.write("      let Secondzero = '';\r\n");
      out.write("      if (month < 10) {\r\n");
      out.write("        Monthzero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (date < 10) {\r\n");
      out.write("        Datezero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (hour < 10) {\r\n");
      out.write("        Hourzero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (minute < 10) {\r\n");
      out.write("        Minutezero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (second < 10) {\r\n");
      out.write("        Secondzero += '0'\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      let day = year + '-' + Monthzero + month + '-' + Datezero + date + '(' + week + ')'; \r\n");
      out.write("      let time = Hourzero + hour + '<b class=\"blink\">:</b>' + Minutezero + minute + '<b class=\"blink\">:</b>' + Secondzero + second;\r\n");
      out.write("      document.querySelector('#local-time1').innerHTML = day;\r\n");
      out.write("      document.querySelector('#local-time2').innerHTML = time;\r\n");
      out.write("    }, 1000);\r\n");
      out.write("    let time = 1800;\r\n");
      out.write("	 setInterval(function() {\r\n");
      out.write("	    	time--\r\n");
      out.write("	    	let hour = Math.floor((time / (60 * 60)) % 60);\r\n");
      out.write("	    	let min = Math.floor((time / 60) % 60);\r\n");
      out.write("	        let sec = Math.floor(time % 60); \r\n");
      out.write("	        let hourzero = '';\r\n");
      out.write("	        let minzero = '';\r\n");
      out.write("	        let seczero = '';\r\n");
      out.write("	        if (hour < 10) {\r\n");
      out.write("	            hourzero += '0'\r\n");
      out.write("           	}\r\n");
      out.write("            if (min < 10) {\r\n");
      out.write("            minzero += '0'\r\n");
      out.write("            }\r\n");
      out.write("            if (sec < 10) {\r\n");
      out.write("             seczero += '0'\r\n");
      out.write("            }\r\n");
      out.write("	    	if(time == 0){\r\n");
      out.write("	    		location.href=\"/customLogout\"\r\n");
      out.write("	    	}\r\n");
      out.write("	    	if(time < 120){\r\n");
      out.write("	    		document.getElementById(\"remain-time\").style.color = \"red\";\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("	    	let remaintime = \"<b>\" + hourzero + hour + \"<b class='blink'>:</b>\" + minzero + min + \"<b class='blink'>:</b>\" + seczero + sec + \"</b>\";\r\n");
      out.write("	    	document.querySelector(\"#remain-time\").innerHTML = remaintime;\r\n");
      out.write("		}, 1000);\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/admin/company/../includes/header.jsp(197,42) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.member.userName");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/admin/company/../includes/header.jsp(212,40) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("										<a href=\"/customLogout\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/admin/company/../includes/header.jsp(215,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("										<a href=\"/customLogin\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent(null);
      // /WEB-INF/views/admin/company/../includes/menu.jsp(7,64) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.member.userName");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/admin/company/../includes/menu.jsp(16,44) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											<a href=\"/customLogout\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("											");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent(null);
      // /WEB-INF/views/admin/company/../includes/menu.jsp(19,11) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											<a href=\"/customLogin\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("											");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/company/myCompany.jsp(74,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/company/myCompany.jsp(74,18) '${bizTypes }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bizTypes }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/admin/company/myCompany.jsp(74,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("bizType");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                	<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bizType.subCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("	                	");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bizType.subCode == company.bizType?\"selected\":\"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bizType.middleName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('>');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bizType.subName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("	                	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/company/myCompany.jsp(90,25) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.companySeal != null and company.companySeal ne ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                       		<img src=\"/display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:replace(company.companySeal, '\\\\', '/')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("\" alt=\"직인\" style=\"max-width:100px;\">\r\n");
          out.write("                       		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
