/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2024-01-17 09:13:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.accountbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class diary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/accountbook/../includes/menu.jsp", Long.valueOf(1703722700391L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar", Long.valueOf(1700568224554L));
    _jspx_dependants.put("/WEB-INF/views/admin/accountbook/../includes/header.jsp", Long.valueOf(1703722700375L));
    _jspx_dependants.put("/WEB-INF/views/admin/accountbook/../includes/footer.jsp", Long.valueOf(1703722700346L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1700568222909L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/spring-security-taglibs-5.0.6.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528824936000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Material Able bootstrap admin template by Codedthemes</title>\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 10]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("      <![endif]-->\r\n");
      out.write("    <!-- Meta -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"keywords\" content=\"bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive\" />\r\n");
      out.write("    <meta name=\"author\" content=\"Codedthemes\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"/resources/assets/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <!-- Google font-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- waves.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("    <!-- Required Fremwork -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- waves.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("    <!-- themify icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/icon/themify-icons/themify-icons.css\">\r\n");
      out.write("    <!-- font-awesome-n -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/font-awesome-n.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- scrollbar.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/jquery.mCustomScrollbar.css\">\r\n");
      out.write("    <!-- Style.css -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/style.css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/assets/js/jquery/jquery.min.js \"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("  .blink {\r\n");
      out.write("        animation: blinker 1s linear infinite;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes blinker {\r\n");
      out.write("        50% {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Pre-loader start -->\r\n");
      out.write("    <div class=\"theme-loader\">\r\n");
      out.write("        <div class=\"loader-track\">\r\n");
      out.write("            <div class=\"preloader-wrapper\">\r\n");
      out.write("                <div class=\"spinner-layer spinner-blue\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"spinner-layer spinner-red\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"spinner-layer spinner-yellow\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"spinner-layer spinner-green\">\r\n");
      out.write("                    <div class=\"circle-clipper left\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"gap-patch\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"circle-clipper right\">\r\n");
      out.write("                        <div class=\"circle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Pre-loader end -->\r\n");
      out.write("    <div id=\"pcoded\" class=\"pcoded\">\r\n");
      out.write("        <div class=\"pcoded-overlay-box\"></div>\r\n");
      out.write("        <div class=\"pcoded-container navbar-wrapper\">\r\n");
      out.write("            <nav class=\"navbar header-navbar pcoded-header\">\r\n");
      out.write("                <div class=\"navbar-wrapper\">\r\n");
      out.write("                    <div class=\"navbar-logo\">\r\n");
      out.write("                        <a class=\"mobile-menu waves-effect waves-light\" id=\"mobile-collapse\" href=\"#!\">\r\n");
      out.write("                            <i class=\"ti-menu\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"mobile-search waves-effect waves-light\">\r\n");
      out.write("                            <div class=\"header-search\">\r\n");
      out.write("                                <div class=\"main-search morphsearch-search\">\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <span class=\"input-group-prepend search-close\"><i class=\"ti-close input-group-text\"></i></span>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Enter Keyword\">\r\n");
      out.write("                                        <span class=\"input-group-append search-btn\"><i class=\"ti-search input-group-text\"></i></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"/admin/\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/assets/images/logo.png\" alt=\"Theme-Logo\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a class=\"mobile-options waves-effect waves-light\">\r\n");
      out.write("                            <i class=\"ti-more\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"navbar-container container-fluid\">\r\n");
      out.write("                        <ul class=\"nav-left\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"sidebar_toggle\"><a href=\"javascript:void(0)\"><i class=\"ti-menu\"></i></a></div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#!\" onclick=\"javascript:toggleFullScreen()\" class=\"waves-effect waves-light\">\r\n");
      out.write("                                    <i class=\"ti-fullscreen\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul class=\"nav-right\">\r\n");
      out.write("                            <li class=\"header-notification\">\r\n");
      out.write("                                <a href=\"#!\" class=\"waves-effect waves-light\">\r\n");
      out.write("                                    <i class=\"ti-bell\"></i>\r\n");
      out.write("                                    <span class=\"badge bg-c-red\"></span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"show-notification\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <h6>Notifications</h6>\r\n");
      out.write("                                        <label class=\"label label-danger\">New</label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"/resources/assets/images/avatar-2.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h5 class=\"notification-user\">John Doe</h5>\r\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\r\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"/resources/assets/images/avatar-4.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h5 class=\"notification-user\">Joseph William</h5>\r\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\r\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"/resources/assets/images/avatar-3.jpg\" alt=\"Generic placeholder image\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <h5 class=\"notification-user\">Sara Soudein</h5>\r\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\r\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"user-profile header-notification\">\r\n");
      out.write("                                <a href=\"#!\" class=\"waves-effect waves-light\">\r\n");
      out.write("                                    <img src=\"/resources/assets/images/avatar-4.jpg\" class=\"img-radius\" alt=\"User-Profile-Image\">\r\n");
      out.write("                                    <span>");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("                                    <i class=\"ti-angle-down\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"show-notification profile-notification\">\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <a href=\"/\">\r\n");
      out.write("                                            <i class=\"ti-user\"></i> MainPage\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        <a href=\"/admin/member/myPage\">\r\n");
      out.write("                                            <i class=\"ti-user\"></i> Profile\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\r\n");
      out.write("                                        ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"pcoded-main-container\">\r\n");
      out.write("                <div class=\"pcoded-wrapper\">\r\n");
      out.write("                    <nav class=\"pcoded-navbar\">\r\n");
      out.write("                        <div class=\"sidebar_toggle\"><a href=\"#\"><i class=\"icon-close icons\"></i></a></div>\r\n");
      out.write("                        <div class=\"pcoded-inner-navbar main-menu\">\r\n");
      out.write("                            \r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("								<div class=\"\">\r\n");
      out.write("                                <div class=\"main-menu-header\">\r\n");
      out.write("                                    <img class=\"img-80 img-radius\" src=\"/resources/assets/images/avatar-4.jpg\" alt=\"User-Profile-Image\">\r\n");
      out.write("                                    <div class=\"user-details\">\r\n");
      out.write("                                        <span id=\"more-details\">");
      if (_jspx_meth_sec_005fauthentication_005f1(_jspx_page_context))
        return;
      out.write("<i class=\"fa fa-caret-down\"></i></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"main-menu-content\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li class=\"more-details\">\r\n");
      out.write("                                        	<a href=\"/\"><i class=\"ti-user\"></i>MainPage</a>\r\n");
      out.write("                                            <a href=\"/admin/member/myPage\"><i class=\"ti-user\"></i>View Profile</a>\r\n");
      out.write("                                            <a href=\"#!\"><i class=\"ti-settings\"></i>Settings</a>\r\n");
      out.write("                                            ");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											");
      if (_jspx_meth_sec_005fauthorize_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pcoded-navigation-label\">Left Time</div>\r\n");
      out.write("                             <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                            	<li class=\"\">\r\n");
      out.write("                        			<a href=\"#\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                   <span class=\"pcoded-micon\"><i class=\"fa fa-clock-o\"></i><b>D</b></span>\r\n");
      out.write("                                   <span id=\"remain-time\" class=\"pcoded-mtext\"></span>\r\n");
      out.write("                                   <span class=\"pcoded-mcaret\"></span> \r\n");
      out.write("                                   </a> \r\n");
      out.write("                                </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                              \r\n");
      out.write("                             <div class=\"pcoded-navigation-label\">Time</div>\r\n");
      out.write("                             <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                             \r\n");
      out.write("                             	<li class=\"active\">\r\n");
      out.write("                        			<a href=\"#\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                   <span class=\"pcoded-micon\"><i class=\"fa fa-calendar\"></i><b>D</b></span>\r\n");
      out.write("                                   <span id=\"local-time1\" class=\"pcoded-mtext\"></span>\r\n");
      out.write("                                   <span class=\"pcoded-mcaret\"></span> \r\n");
      out.write("                                   </a> \r\n");
      out.write("                                </li>\r\n");
      out.write("                             	<li class=\"active\">\r\n");
      out.write("                        			<a href=\"#\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                   <span class=\"pcoded-micon\"><i class=\"fa fa-clock-o\"></i><b>D</b></span>\r\n");
      out.write("                                   <span id=\"local-time2\" class=\"pcoded-mtext\"></span>\r\n");
      out.write("                                   <span class=\"pcoded-mcaret\"></span> \r\n");
      out.write("                                   </a> \r\n");
      out.write("                                </li>\r\n");
      out.write("                             \r\n");
      out.write("                             </ul>\r\n");
      out.write("                            <div class=\"pcoded-navigation-label\">Navigation</div>\r\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                                <li class=\"active\">\r\n");
      out.write("                                    <a href=\"/admin/\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-home\"></i><b>D</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">대시보드</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                       </a>\r\n");
      out.write("                                    \r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'diary'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"/admin/accountbook/diary\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-agenda\"></i><b>D</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">다이어리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'board'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"/admin/board/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-list\"></i><b>D</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">게시판관리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'trade'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                     <a href=\"/admin/trade/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                         <span class=\"pcoded-micon\"><i class=\"ti-money\"></i></span>\r\n");
      out.write("                                         <span class=\"pcoded-mtext\">거래명세서</span>\r\n");
      out.write("                                         <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                     </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                  <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'log'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                     <a href=\"/admin/log/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                         <span class=\"pcoded-micon\"><i class=\"ti-agenda\"></i></span>\r\n");
      out.write("                                         <span class=\"pcoded-mtext\">업무일지</span>\r\n");
      out.write("                                         <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                     </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            \r\n");
      out.write("							<div class=\"pcoded-navigation-label }\">UI Element</div>\r\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                                <li class=\"pcoded-hasmenu ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'major' || active == 'member' || active == 'master' || active == 'myCompany' ? 'active pcode-trigger':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-layout-grid2-alt\"></i><b>BC</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">기본정보관리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"pcoded-submenu\">\r\n");
      out.write("	                                     <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'myCompany'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/company/myCompany\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">회사정보관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'major'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/major/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">메이지정보관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'master'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/master/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">마스터코드관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                       </li>\r\n");
      out.write("                                         <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'member'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/member/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">직원관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                       </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            	<div class=\"pcoded-navigation-label }\">UI Element</div>\r\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                                <li class=\"pcoded-hasmenu ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'product' || active == 'master' || active == 'company' ? 'active pcode-trigger':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-layout-grid2-alt\"></i><b>BC</b></span>\r\n");
      out.write("                                        <span class=\"pcoded-mtext\">업무관리</span>\r\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"pcoded-submenu\">\r\n");
      out.write("	                                     <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'company'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/company/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">납품업체관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active == 'product'? 'active':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                            <a href=\"/admin/product/list\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                <span class=\"pcoded-mtext\">물품관리</span>\r\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                       	</li>         \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <div class=\"pcoded-content\">\r\n");
      out.write("                        <!-- Page-header start -->\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <div class=\"page-block\">\r\n");
      out.write("                                <div class=\"row align-items-center\">\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                        <div class=\"page-header-title\">\r\n");
      out.write("                                            <h5 class=\"m-b-10\">Dashboard</h5>\r\n");
      out.write("                                            <p class=\"m-b-0\">Welcome to Material Able</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <ul class=\"breadcrumb\">\r\n");
      out.write("                                            <li class=\"breadcrumb-item\">\r\n");
      out.write("                                                <a href=\"/admin/\"> <i class=\"fa fa-home\"></i> </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"breadcrumb-item\"><a href=\"#!\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${active}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Page-header end -->\r\n");
      out.write("                        <div class=\"pcoded-inner-content\">\r\n");
      out.write("                            <!-- Main-body start -->\r\n");
      out.write("                            <div class=\"main-body\">\r\n");
      out.write("                                <div class=\"page-wrapper\">\r\n");
      out.write("                                    <!-- Page-body start -->\r\n");
      out.write("                                    <div class=\"page-body\">\r\n");
      out.write("                                    <!-- header End -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- fullcalendar CDN -->\r\n");
      out.write("<link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.css' rel='stylesheet' />\r\n");
      out.write("<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.js'></script>\r\n");
      out.write("<!-- fullcalendar 언어 CDN -->\r\n");
      out.write("<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/locales-all.min.js'></script>\r\n");
      out.write("<!-- axios -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("<!-- 부트스트랩CDN -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<div class=\"col-sm-12\">\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("			<div class=\"card-header\">\r\n");
      out.write("				<h5>Hello card</h5>\r\n");
      out.write("				<span>lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("					elit</span>\r\n");
      out.write("				<div class=\"card-header-right\">\r\n");
      out.write("					<ul class=\"list-unstyled card-option\">\r\n");
      out.write("						<li><i class=\"fa fa fa-wrench open-card-option\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-window-maximize full-card\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-minus minimize-card\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-refresh reload-card\"></i></li>\r\n");
      out.write("						<li><i class=\"fa fa-trash close-card\"></i></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card-block\">\r\n");
      out.write("				<div id='calendar'></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 부트스트랩 modal 부분 -->\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\r\n");
      out.write("	aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	<div class=\"modal-dialog\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<div class=\"modal-header\">\r\n");
      out.write("				<h5 class=\"modal-title\" id=\"exampleModalLabel\">일정 추가하기</h5>\r\n");
      out.write("				<span class=\"ti-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body form-material\">\r\n");
      out.write("				<div class=\"form-group form-primary\">\r\n");
      out.write("		          <input type=\"text\" id=\"title\" class=\"form-control\">\r\n");
      out.write("		          <span class=\"form-bar\"></span>\r\n");
      out.write("		          <label class=\"float-label\">일정제목</label>\r\n");
      out.write("		        </div>\r\n");
      out.write("				<div class=\"form-group form-primary\">\r\n");
      out.write("		          <input type=\"datetime-local\" id=\"start\" class=\"form-control\">\r\n");
      out.write("		          <span class=\"form-bar\"></span>\r\n");
      out.write("		          <label class=\"float-label\">시작시간</label>\r\n");
      out.write("		        </div>\r\n");
      out.write("				<div class=\"form-group form-primary\">\r\n");
      out.write("		          <input type=\"datetime-local\" id=\"end\" class=\"form-control\">\r\n");
      out.write("		          <span class=\"form-bar\"></span>\r\n");
      out.write("		          <label class=\"float-label\">종료시간</label>\r\n");
      out.write("		        </div>\r\n");
      out.write("				<div class=\"form-group form-primary\">\r\n");
      out.write("		          <select id=\"color\" class=\"form-control\">\r\n");
      out.write("					<option value=\"red\">빨강색</option>\r\n");
      out.write("					<option value=\"orange\">주황색</option>\r\n");
      out.write("					<option value=\"yellow\">노랑색</option>\r\n");
      out.write("					<option value=\"green\">초록색</option>\r\n");
      out.write("					<option value=\"blue\">파랑색</option>\r\n");
      out.write("					<option value=\"indigo\">남색</option>\r\n");
      out.write("					<option value=\"purple\">보라색</option>\r\n");
      out.write("				  </select>\r\n");
      out.write("		          <span class=\"form-bar\"></span>\r\n");
      out.write("		          <label class=\"float-label\">배경색상</label>\r\n");
      out.write("		        </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary\" id=\"saveChanges\">추가</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  (function(){\r\n");
      out.write("    $(function(){\r\n");
      out.write("   	  let _csrf = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   	  let _csrf_header = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("   	  \r\n");
      out.write("   	  \r\n");
      out.write("      // calendar element 취득\r\n");
      out.write("      var calendarEl = $('#calendar')[0];\r\n");
      out.write("      // full-calendar 생성하기\r\n");
      out.write("      var calendar = new FullCalendar.Calendar(calendarEl, {\r\n");
      out.write("        googleCalendarApiKey: '',// 여기에 구글캘린더 api키 입력하시면 됩니다.\r\n");
      out.write("        height: '700px', // calendar 높이 설정\r\n");
      out.write("        expandRows: true, // 화면에 맞게 높이 재설정\r\n");
      out.write("        slotMinTime: '08:00', // Day 캘린더에서 시작 시간\r\n");
      out.write("        slotMaxTime: '20:00', // Day 캘린더에서 종료 시간\r\n");
      out.write("        customButtons:{\r\n");
      out.write("          myCustomButton:{\r\n");
      out.write("            text:\"일정추가\",\r\n");
      out.write("            click : function(){\r\n");
      out.write("       		  $(\"#start\").addClass('fill');\r\n");
      out.write("       		  $(\"#end\").addClass('fill');\r\n");
      out.write("       		  $(\"#color\").addClass('fill');\r\n");
      out.write("       		  \r\n");
      out.write("              //부트스트랩 모달 열기\r\n");
      out.write("              $(\"#exampleModal\").modal(\"show\");              \r\n");
      out.write("            }\r\n");
      out.write("          },\r\n");
      out.write("          mySaveButton:{\r\n");
      out.write("            text:\"저장\",\r\n");
      out.write("            click: async function () {\r\n");
      out.write("              if (confirm(\"저장하시겠습니까?\")) {\r\n");
      out.write("                //지금까지 생성된 모든 이벤트 저장하기\r\n");
      out.write("                var allEvent = calendar.getEvents();\r\n");
      out.write("                console.log(\"모든 이벤트들\", allEvent);\r\n");
      out.write("                //이벤트 저장하기\r\n");
      out.write("                const saveEvent = await axios({\r\n");
      out.write("                  method: \"POST\",\r\n");
      out.write("                  url: \"/admin/fullcalendar/new\",\r\n");
      out.write("                  data: allEvent,\r\n");
      out.write("				  headers: {\r\n");
      out.write("						\"Content-Type\" : \"application/json; charset=utf-8\",\r\n");
      out.write("						[_csrf_header]: _csrf\r\n");
      out.write("				  }\r\n");
      out.write("                });\r\n");
      out.write("              }\r\n");
      out.write("            },\r\n");
      out.write("          }\r\n");
      out.write("        },\r\n");
      out.write("        // 해더에 표시할 툴바\r\n");
      out.write("        headerToolbar: {\r\n");
      out.write("          left: 'prev,next today,myCustomButton,mySaveButton',\r\n");
      out.write("          center: 'title',\r\n");
      out.write("          right: 'dayGridMonth,timeGridWeek,timeGridDay'\r\n");
      out.write("        },\r\n");
      out.write("        initialView: 'dayGridMonth', // 초기 로드 될때 보이는 캘린더 화면(기본 설정: 달)\r\n");
      out.write("        // initialDate: '2021-07-15', // 초기 날짜 설정 (설정하지 않으면 오늘 날짜가 보인다.)\r\n");
      out.write("        navLinks: false, // 날짜를 선택하면 Day 캘린더나 Week 캘린더로 링크\r\n");
      out.write("        editable: true, // 수정 가능?\r\n");
      out.write("        selectable: true, // 달력 일자 드래그 설정가능\r\n");
      out.write("        nowIndicator: true, // 현재 시간 마크\r\n");
      out.write("        dayMaxEvents: false, // 이벤트가 오버되면 높이 제한 (+ 몇 개식으로 표현)\r\n");
      out.write("        locale: 'ko', // 한국어 설정\r\n");
      out.write("        selectMirror: true,\r\n");
      out.write("        eventAdd: function(obj) { // 이벤트가 추가되면 발생하는 이벤트\r\n");
      out.write("          console.log(\"eventAdd\" + obj);\r\n");
      out.write("        },\r\n");
      out.write("        eventChange: function(obj) { // 이벤트가 수정되면 발생하는 이벤트\r\n");
      out.write("          console.log(\"eventChange\" + obj);\r\n");
      out.write("        },\r\n");
      out.write("        eventRemove: function(obj){ // 이벤트가 삭제되면 발생하는 이벤트\r\n");
      out.write("          console.log(\"eventRemove\" + obj);\r\n");
      out.write("        },\r\n");
      out.write("        eventClick: function(obj){ // 이벤트가 클릭하면 발생하는 이벤트\r\n");
      out.write("        	if(confirm('정말로 삭제하시겠습니까?')){\r\n");
      out.write("        		obj.event.remove();	\r\n");
      out.write("        	}\r\n");
      out.write("          console.log(\"eventClick\" + obj);\r\n");
      out.write("        },   \r\n");
      out.write("        eventDrop: function(arg){\r\n");
      out.write("      	  console.log(\"eventDrop:\"+arg);\r\n");
      out.write("        },\r\n");
      out.write("        eventResize: function(arg){\r\n");
      out.write("      	  console.log(\"eventResize:\"+arg);\r\n");
      out.write("        },     \r\n");
      out.write("        select: function(arg) { // 캘린더에서 드래그로 이벤트를 생성할 수 있다.\r\n");
      out.write("          var title = prompt('Event Title:');\r\n");
      out.write("          if (title) {\r\n");
      out.write("            calendar.addEvent({\r\n");
      out.write("              title: title,\r\n");
      out.write("              start: arg.start,\r\n");
      out.write("              end: arg.end,\r\n");
      out.write("              allDay: arg.allDay\r\n");
      out.write("            })\r\n");
      out.write("          }\r\n");
      out.write("          calendar.unselect()\r\n");
      out.write("        },\r\n");
      out.write("        //데이터 가져오는 이벤트\r\n");
      out.write("        eventSources:[\r\n");
      out.write("          {\r\n");
      out.write("            events: async function (info, successCallback, failureCallback) {\r\n");
      out.write("          const eventResult = await axios({\r\n");
      out.write("            method: \"GET\",\r\n");
      out.write("            url: \"/admin/fullcalendar/eventData\",\r\n");
      out.write("          });\r\n");
      out.write("          const eventData = eventResult.data;\r\n");
      out.write("          //이벤트에 넣을 배열 선언하기\r\n");
      out.write("          const eventArray = [];\r\n");
      out.write("          \r\n");
      out.write("          eventData.forEach((res) => {\r\n");
      out.write("        	/* if(res.start.substr(0, 10) != res.end.substr(0, 10)){\r\n");
      out.write("        		res.start = res.start.substr(0, 10);\r\n");
      out.write("        		res.end = res.end.substr(0, 10);\r\n");
      out.write("        	}  */\r\n");
      out.write("\r\n");
      out.write("            eventArray.push({\r\n");
      out.write("              id: res.id,\r\n");
      out.write("              title: res.title,\r\n");
      out.write("              start: res.start,\r\n");
      out.write("              end: res.end,\r\n");
      out.write("              backgroundColor: res.backgroundColor,\r\n");
      out.write("            });\r\n");
      out.write("          });\r\n");
      out.write("          successCallback(eventArray);\r\n");
      out.write("        \r\n");
      out.write("        },\r\n");
      out.write("          },\r\n");
      out.write("            {\r\n");
      out.write("              googleCalendarId : 'ko.south_korea.official#holiday@group.v.calendar.google.com',\r\n");
      out.write("              backgroundColor: 'red',\r\n");
      out.write("            }\r\n");
      out.write("        ]\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //모달창 이벤트\r\n");
      out.write("      $(\"#saveChanges\").on(\"click\", function () {\r\n");
      out.write("            var eventData = {\r\n");
      out.write("              title: $(\"#title\").val(),\r\n");
      out.write("              start: $(\"#start\").val(),\r\n");
      out.write("              end: $(\"#end\").val(),\r\n");
      out.write("              color: $(\"#color\").val(),\r\n");
      out.write("            };\r\n");
      out.write("            //빈값입력시 오류\r\n");
      out.write("            if (\r\n");
      out.write("              eventData.title == \"\" ||\r\n");
      out.write("              eventData.start == \"\" ||\r\n");
      out.write("              eventData.end == \"\"\r\n");
      out.write("            ) {\r\n");
      out.write("              alert(\"입력하지 않은 값이 있습니다.\");\r\n");
      out.write("\r\n");
      out.write("              //끝나는 날짜가 시작하는 날짜보다 값이 크면 안됨\r\n");
      out.write("            } else if ($(\"#start\").val() > $(\"#end\").val()) {\r\n");
      out.write("              alert(\"시간을 잘못입력 하셨습니다.\");\r\n");
      out.write("            } else {\r\n");
      out.write("              // 이벤트 추가\r\n");
      out.write("              calendar.addEvent(eventData);\r\n");
      out.write("              $(\"#exampleModal\").modal(\"hide\");\r\n");
      out.write("              $(\"#title\").val(\"\");\r\n");
      out.write("              $(\"#start\").val(\"\");\r\n");
      out.write("              $(\"#end\").val(\"\");\r\n");
      out.write("              $(\"#color\").val(\"\");\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("      // 캘린더 랜더링\r\n");
      out.write("      calendar.render();\r\n");
      out.write("    });\r\n");
      out.write("  })();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer Start -->\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Page-body end -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"styleSelector\"> </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Warning Section Starts -->\r\n");
      out.write("    <!-- Older IE warning message -->\r\n");
      out.write("    <!--[if lt IE 10]>\r\n");
      out.write("<div class=\"ie-warning\">\r\n");
      out.write("    <h1>Warning!!</h1>\r\n");
      out.write("    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>\r\n");
      out.write("    <div class=\"iew-container\">\r\n");
      out.write("        <ul class=\"iew-download\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://www.google.com/chrome/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/chrome.png\" alt=\"Chrome\">\r\n");
      out.write("                    <div>Chrome</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"https://www.mozilla.org/en-US/firefox/new/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/firefox.png\" alt=\"Firefox\">\r\n");
      out.write("                    <div>Firefox</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://www.opera.com\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/opera.png\" alt=\"Opera\">\r\n");
      out.write("                    <div>Opera</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"https://www.apple.com/safari/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/safari.png\" alt=\"Safari\">\r\n");
      out.write("                    <div>Safari</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/ie.png\" alt=\"\">\r\n");
      out.write("                    <div>IE (9 & above)</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p>Sorry for the inconvenience!</p>\r\n");
      out.write("</div>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("    <!-- Warning Section Ends -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Required Jquery -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/jquery-ui/jquery-ui.min.js \"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/popper.js/popper.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/bootstrap/js/bootstrap.min.js \"></script>\r\n");
      out.write("    <!-- waves js -->\r\n");
      out.write("    <script src=\"/resources/assets/pages/waves/js/waves.min.js\"></script>\r\n");
      out.write("    <!-- jquery slimscroll js -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/jquery-slimscroll/jquery.slimscroll.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- slimscroll js -->\r\n");
      out.write("    <script src=\"/resources/assets/js/jquery.mCustomScrollbar.concat.min.js \"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- menu js -->\r\n");
      out.write("    <script src=\"/resources/assets/js/pcoded.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/assets/js/vertical/vertical-layout.min.js \"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/assets/js/script.js \"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("    $(\".sidebar-nav\")\r\n");
      out.write("    .attr(\"class\", \"sidebar-nav navbar-collapse collapse\")\r\n");
      out.write("    .attr(\"aria-expanded\", \"false\")\r\n");
      out.write("    .attr(\"style\", \"height:1px\");\r\n");
      out.write("           \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    setInterval(function () {\r\n");
      out.write("      let now = new Date();\r\n");
      out.write("      let year = now.getFullYear();\r\n");
      out.write("      let month = now.getMonth() + 1;\r\n");
      out.write("      let weekday = ['일', '월', '화', '수', '목', '금', '토'];\r\n");
      out.write("      let week = weekday[now.getDay()];\r\n");
      out.write("      let date = now.getDate();\r\n");
      out.write("      let hour = now.getHours();\r\n");
      out.write("      let minute = now.getMinutes();\r\n");
      out.write("      let second = now.getSeconds();\r\n");
      out.write("      let Monthzero = '';\r\n");
      out.write("      let Datezero = '';\r\n");
      out.write("      let Hourzero = '';\r\n");
      out.write("      let Minutezero = '';\r\n");
      out.write("      let Secondzero = '';\r\n");
      out.write("      if (month < 10) {\r\n");
      out.write("        Monthzero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (date < 10) {\r\n");
      out.write("        Datezero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (hour < 10) {\r\n");
      out.write("        Hourzero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (minute < 10) {\r\n");
      out.write("        Minutezero += '0'\r\n");
      out.write("      }\r\n");
      out.write("      if (second < 10) {\r\n");
      out.write("        Secondzero += '0'\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      let day = year + '-' + Monthzero + month + '-' + Datezero + date + '(' + week + ')'; \r\n");
      out.write("      let time = Hourzero + hour + '<b class=\"blink\">:</b>' + Minutezero + minute + '<b class=\"blink\">:</b>' + Secondzero + second;\r\n");
      out.write("      document.querySelector('#local-time1').innerHTML = day;\r\n");
      out.write("      document.querySelector('#local-time2').innerHTML = time;\r\n");
      out.write("    }, 1000);\r\n");
      out.write("    let time = 1800;\r\n");
      out.write("	 setInterval(function() {\r\n");
      out.write("	    	time--\r\n");
      out.write("	    	let hour = Math.floor((time / (60 * 60)) % 60);\r\n");
      out.write("	    	let min = Math.floor((time / 60) % 60);\r\n");
      out.write("	        let sec = Math.floor(time % 60); \r\n");
      out.write("	        let hourzero = '';\r\n");
      out.write("	        let minzero = '';\r\n");
      out.write("	        let seczero = '';\r\n");
      out.write("	        if (hour < 10) {\r\n");
      out.write("	            hourzero += '0'\r\n");
      out.write("           	}\r\n");
      out.write("            if (min < 10) {\r\n");
      out.write("            minzero += '0'\r\n");
      out.write("            }\r\n");
      out.write("            if (sec < 10) {\r\n");
      out.write("             seczero += '0'\r\n");
      out.write("            }\r\n");
      out.write("	    	if(time == 0){\r\n");
      out.write("	    		location.href=\"/customLogout\"\r\n");
      out.write("	    	}\r\n");
      out.write("	    	if(time < 120){\r\n");
      out.write("	    		document.getElementById(\"remain-time\").style.color = \"red\";\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("	    	let remaintime = \"<b>\" + hourzero + hour + \"<b class='blink'>:</b>\" + minzero + min + \"<b class='blink'>:</b>\" + seczero + sec + \"</b>\";\r\n");
      out.write("	    	document.querySelector(\"#remain-time\").innerHTML = remaintime;\r\n");
      out.write("		}, 1000);\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/admin/accountbook/../includes/header.jsp(197,42) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.member.userName");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/admin/accountbook/../includes/header.jsp(212,40) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("										<a href=\"/customLogout\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/admin/accountbook/../includes/header.jsp(215,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("										<a href=\"/customLogin\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent(null);
      // /WEB-INF/views/admin/accountbook/../includes/menu.jsp(7,64) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.member.userName");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/admin/accountbook/../includes/menu.jsp(16,44) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											<a href=\"/customLogout\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("											");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent(null);
      // /WEB-INF/views/admin/accountbook/../includes/menu.jsp(19,11) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											<a href=\"/customLogin\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
        out.write("											");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f3_reused);
    }
    return false;
  }
}
