/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2024-01-17 09:13:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/calendar-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/december/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1700568222909L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Material Able bootstrap admin template by Codedthemes</title>\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 10]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("      <![endif]-->\r\n");
      out.write("      <!-- Meta -->\r\n");
      out.write("      <meta charset=\"utf-8\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\r\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("\r\n");
      out.write("      <meta name=\"keywords\" content=\"bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive\" />\r\n");
      out.write("      <meta name=\"author\" content=\"Codedthemes\" />\r\n");
      out.write("      <!-- Favicon icon -->\r\n");
      out.write("\r\n");
      out.write("      <link rel=\"icon\" href=\"/resources/assets/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("      <!-- Google font-->\r\n");
      out.write("      <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("      <!-- Required Fremwork -->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("      <!-- waves.css -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"/resources/assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("      <!-- themify-icons line icon -->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/icon/themify-icons/themify-icons.css\">\r\n");
      out.write("      <!-- ico font -->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/icon/icofont/css/icofont.css\">\r\n");
      out.write("      <!-- Font Awesome -->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/icon/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("      <!-- Style.css -->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body themebg-pattern=\"theme1\">\r\n");
      out.write("  <!-- Pre-loader start -->\r\n");
      out.write("  <div class=\"theme-loader\">\r\n");
      out.write("      <div class=\"loader-track\">\r\n");
      out.write("          <div class=\"preloader-wrapper\">\r\n");
      out.write("              <div class=\"spinner-layer spinner-blue\">\r\n");
      out.write("                  <div class=\"circle-clipper left\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"gap-patch\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"circle-clipper right\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"spinner-layer spinner-red\">\r\n");
      out.write("                  <div class=\"circle-clipper left\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"gap-patch\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"circle-clipper right\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"spinner-layer spinner-yellow\">\r\n");
      out.write("                  <div class=\"circle-clipper left\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"gap-patch\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"circle-clipper right\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"spinner-layer spinner-green\">\r\n");
      out.write("                  <div class=\"circle-clipper left\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"gap-patch\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"circle-clipper right\">\r\n");
      out.write("                      <div class=\"circle\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Pre-loader end -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"login-block\">\r\n");
      out.write("        <!-- Container-fluid starts -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-12\">\r\n");
      out.write("                    <!-- Authentication card start -->\r\n");
      out.write("\r\n");
      out.write("                        <form class=\"md-float-material form-material\" method=\"post\" action=\"/login\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <div class=\"text-center\">\r\n");
      out.write("                                <img src=\"/resources/assets/images/logo.png\" alt=\"logo.png\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"auth-box card\">\r\n");
      out.write("                                <div class=\"card-block\">\r\n");
      out.write("                                    <div class=\"row m-b-20\">\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <h3 class=\"text-center\">Sign In</h3>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group form-primary\">\r\n");
      out.write("                                        <input type=\"text\" name=\"username\" class=\"form-control\" required=\"required\">\r\n");
      out.write("                                        <span class=\"form-bar\"></span>\r\n");
      out.write("                                        <label class=\"float-label\">Your name</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group form-primary\">\r\n");
      out.write("                                        <input type=\"password\" name=\"password\" class=\"form-control\" required=\"required\">\r\n");
      out.write("                                        <span class=\"form-bar\"></span>\r\n");
      out.write("                                        <label class=\"float-label\">Password</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row m-t-25 text-left\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"checkbox-fade fade-in-primary d-\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\" name=\"remember-me\">\r\n");
      out.write("                                                    <span class=\"cr\"><i class=\"cr-icon icofont icofont-ui-check txt-primary\"></i></span>\r\n");
      out.write("                                                    <span class=\"text-inverse\">Remember me</span>\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"forgot-phone text-right f-right\">\r\n");
      out.write("                                                \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row m-t-30\">\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20\">Sign in</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <hr/>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-10\">\r\n");
      out.write("                                            <p class=\"text-inverse text-left m-b-0\">Thank you.</p>\r\n");
      out.write("                                            <p class=\"text-inverse text-left\"><a href=\"/\"><b>Back to website</b></a></p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-2\">\r\n");
      out.write("                                            <img src=\"/resources/assets/images/auth/Logo-small-bottom.png\" alt=\"small-logo.png\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <!-- end of form -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- end of col-sm-12 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end of row -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end of container-fluid -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Warning Section Starts -->\r\n");
      out.write("    <!-- Older IE warning message -->\r\n");
      out.write("    <!--[if lt IE 10]>\r\n");
      out.write("<div class=\"ie-warning\">\r\n");
      out.write("    <h1>Warning!!</h1>\r\n");
      out.write("    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>\r\n");
      out.write("    <div class=\"iew-container\">\r\n");
      out.write("        <ul class=\"iew-download\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://www.google.com/chrome/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/chrome.png\" alt=\"Chrome\">\r\n");
      out.write("                    <div>Chrome</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"https://www.mozilla.org/en-US/firefox/new/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/firefox.png\" alt=\"Firefox\">\r\n");
      out.write("                    <div>Firefox</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://www.opera.com\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/opera.png\" alt=\"Opera\">\r\n");
      out.write("                    <div>Opera</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"https://www.apple.com/safari/\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/safari.png\" alt=\"Safari\">\r\n");
      out.write("                    <div>Safari</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">\r\n");
      out.write("                    <img src=\"/resources/assets/images/browser/ie.png\" alt=\"\">\r\n");
      out.write("                    <div>IE (9 & above)</div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p>Sorry for the inconvenience!</p>\r\n");
      out.write("</div>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!-- Warning Section Ends -->\r\n");
      out.write("<!-- Required Jquery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/assets/js/jquery/jquery.min.js \"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/assets/js/jquery-ui/jquery-ui.min.js \"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/assets/js/popper.js/popper.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/assets/js/bootstrap/js/bootstrap.min.js \"></script>\r\n");
      out.write("<!-- waves js -->\r\n");
      out.write("<script src=\"/resources/assets/pages/waves/js/waves.min.js\"></script>\r\n");
      out.write("<!-- jquery slimscroll js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/assets/js/jquery-slimscroll/jquery.slimscroll.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/assets/js/common-pages.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
